version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: docker build
          command: util/docker_build.sh ergodox_ez:default
      - store_artifacts:
          path: .build/ergodox_ez_default.hex